//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WebFresher052023.CTM.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WebFresher052023.CTM.Domain.Resource.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng &lt;{0}&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string Code_Exist {
            get {
                return ResourceManager.GetString("Code_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng &lt;{0}&gt; không tồn tại trong hệ thống..
        /// </summary>
        public static string Code_Not_Exist {
            get {
                return ResourceManager.GetString("Code_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[A-Z]+\d*-\d+$.
        /// </summary>
        public static string Code_Regex {
            get {
                return ResourceManager.GetString("Code_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa từ danh sách rỗng!.
        /// </summary>
        public static string Delete_Empty_Error {
            get {
                return ResourceManager.GetString("Delete_Empty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban &lt;{0}&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string Department_Exist {
            get {
                return ResourceManager.GetString("Department_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban &lt;{0}&gt; không tồn tại trong hệ thống..
        /// </summary>
        public static string Department_Not_Exist {
            get {
                return ResourceManager.GetString("Department_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên &lt;{0}&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string Employee_Exist {
            get {
                return ResourceManager.GetString("Employee_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên &lt;{0}&gt; không tồn tại trong hệ thống..
        /// </summary>
        public static string Employee_Not_Exist {
            get {
                return ResourceManager.GetString("Employee_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string Excel_Employee_Code_Header_Name {
            get {
                return ResourceManager.GetString("Excel_Employee_Code_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề &lt;{0}&gt; đã bị trùng..
        /// </summary>
        public static string Excel_Header_Duplicate {
            get {
                return ResourceManager.GetString("Excel_Header_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tiêu đề không được để trống..
        /// </summary>
        public static string Excel_Header_Empty {
            get {
                return ResourceManager.GetString("Excel_Header_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tiếp tục nhập dữ liệu nếu các cột bắt buộc chưa được ghép với cột tương ứng trên tệp Excel. Vui lòng kiểm tra lại..
        /// </summary>
        public static string Excel_Header_Required_Not_Map {
            get {
                return ResourceManager.GetString("Excel_Header_Required_Not_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng dữ liệu trùng với dòng số &lt;{0}&gt;..
        /// </summary>
        public static string Excel_Row_Duplicate {
            get {
                return ResourceManager.GetString("Excel_Row_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài nguyên..
        /// </summary>
        public static string Exception_NotFound_Default {
            get {
                return ResourceManager.GetString("Exception_NotFound_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống, vui lòng liên hệ MISA để được trợ giúp..
        /// </summary>
        public static string Exception_System_Default {
            get {
                return ResourceManager.GetString("Exception_System_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ, vui lòng kiểm tra lại..
        /// </summary>
        public static string Exception_Validate_Default {
            get {
                return ResourceManager.GetString("Exception_Validate_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp đính kèm không hợp lệ, chỉ chấp file .xlsx..
        /// </summary>
        public static string Format_Excel_Error {
            get {
                return ResourceManager.GetString("Format_Excel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đã ghi nhận lệnh nhập khẩu..
        /// </summary>
        public static string Import_Excel_Request_Success {
            get {
                return ResourceManager.GetString("Import_Excel_Request_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vượt quá kích thước file cho phép..
        /// </summary>
        public static string Max_Size_File_Error {
            get {
                return ResourceManager.GetString("Max_Size_File_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên làm việc của bạn đã hết, vui lòng reload trang để bắt đầu phiên mới..
        /// </summary>
        public static string Session_Is_Over {
            get {
                return ResourceManager.GetString("Session_Is_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet không có dữ liệu..
        /// </summary>
        public static string Sheet_Is_Empty {
            get {
                return ResourceManager.GetString("Sheet_Is_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên không được phép để trống..
        /// </summary>
        public static string Validate_ThreadName_NotNull {
            get {
                return ResourceManager.GetString("Validate_ThreadName_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi nhập liệu từ người dùng..
        /// </summary>
        public static string Validate_User_Input_Error {
            get {
                return ResourceManager.GetString("Validate_User_Input_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code &lt;{0}&gt; không đúng định dạng. Ví dụ đúng: NV-1001, AB2-999..
        /// </summary>
        public static string Wrong_Format_Code {
            get {
                return ResourceManager.GetString("Wrong_Format_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai định dạng ngày tháng, định dạng đúng: &lt;{0}&gt;..
        /// </summary>
        public static string Wrong_Format_Date {
            get {
                return ResourceManager.GetString("Wrong_Format_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng..
        /// </summary>
        public static string Wrong_Format_Email {
            get {
                return ResourceManager.GetString("Wrong_Format_Email", resourceCulture);
            }
        }
    }
}
