export var columnsInfo = [
  {
    id: "EmployeeCode",
    name: "Mã nhân viên",
    size: 150,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "FullName",
    name: "Tên nhân viên",
    size: 250,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "Gender",
    name: "Giới tính",
    size: 120,
    textAlign: "left",
    format: "gender",
    isShow: true,
    isPin: false,
  },
  {
    id: "DateOfBirth",
    name: "Ngày sinh",
    size: 150,
    textAlign: "center",
    format: "date",
    isShow: true,
    isPin: false,
  },
  {
    id: "IdentityNumber",
    name: "Số CMND",
    size: 200,
    textAlign: "right",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "IdentityDate",
    name: "Ngày cấp",
    size: 150,
    textAlign: "center",
    format: "date",
    isShow: true,
    isPin: false,
  },
  {
    id: "IdentityPlace",
    name: "Nơi cấp",
    size: 150,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "Position",
    name: "Chức danh",
    size: 250,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "DepartmentCode",
    name: "Mã đơn vị",
    size: 150,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "DepartmentName",
    name: "Tên đơn vị",
    size: 250,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "SupplierCustomerGroup",
    name: "Nhóm KH, NCC",
    size: 200,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "PayAccount",
    name: "TK công nợ phải trả",
    size: 200,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "ReceiveAccount",
    name: "TK công nợ phải thu",
    size: 200,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "Salary",
    name: "Lương thỏa thuận",
    size: 200,
    textAlign: "right",
    format: "currency",
    isShow: true,
    isPin: false,
  },
  {
    id: "SalaryCoefficients",
    name: "Hệ số lương",
    size: 200,
    textAlign: "right",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "SalaryPaidForInsurance",
    name: "Lương đóng bảo hiểm",
    size: 200,
    textAlign: "right",
    format: "currency",
    isShow: true,
    isPin: false,
  },
  {
    id: "PersonalTaxCode",
    name: "Mã số thuế",
    size: 150,
    textAlign: "right",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "TypeOfContract",
    name: "Loại hợp đồng",
    size: 150,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "NumberOfDependents",
    name: "Số người phụ thuộc",
    size: 200,
    textAlign: "right",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "AccountNumber",
    name: "Số tài khoản",
    size: 150,
    textAlign: "right",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "BankName",
    name: "Tên ngân hàng",
    size: 250,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "BankBranch",
    name: "Chi nhánh TK ngân hàng",
    size: 250,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "BankProvince",
    name: "Tỉnh/TP ngân hàng",
    size: 180,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "ContactAddress",
    name: "Địa chỉ",
    size: 200,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "ContactPhoneNumber",
    name: "ĐT di động",
    size: 150,
    textAlign: "right",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "ContactLandlinePhoneNumber",
    name: "ĐT cố định",
    size: 150,
    textAlign: "right",
    format: "text",
    isShow: true,
    isPin: false,
  },
  {
    id: "ContactEmail",
    name: "Email",
    size: 200,
    textAlign: "left",
    format: "text",
    isShow: true,
    isPin: false,
  },
];
